### PR TITLE
Directories should be executable

### PR DESCRIPTION
**Pull request by jeffglover**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
Logrotate requires 644

**Comment by jeffglover** [comment]
I'd like to be able to view logs from outside the container. As I get permission denied in the log directories until I add the executable bit to the log/ directory. Then it gets reset every time I reboot the container.

**Comment by aptalca** [comment]
if non-root users have read-write permissions, logrotate complains and fails to run, so they have to remain 644.

However, you use the root user to view those files outside of the container, or with sudo

**Comment by jeffglover** [comment]
Ah, maybe the intent of my original commit is unclear. I was effectively making the directories, 755 and files 644. This maintains the original intent where both files and directories have read-write for root only, while group and others still have read-only. But with the added benefit that directories are now properly executable so that a regular user may enter them for viewing purposes. https://superuser.com/a/91966

**Comment by jeffglover** [comment]
Here's some tests from within the container:
### First purposely breaking it
```
root@efa02cd3fb70:/$ chmod -R 777 /config/log
root@efa02cd3fb70:/$ logrotate -d /etc/logrotate.conf 
reading config file /etc/logrotate.conf
including /etc/logrotate.d
reading config file acpid
reading config file fail2ban
reading config file lerotate
reading config file nginx
reading config file php-fpm7
Allocating hash table for state file, size 64 entries

Handling 5 logs

rotating pattern: /var/log/acpid.log  weekly (4 rotations)
empty log files are not rotated, old logs are removed
considering log /var/log/acpid.log
  log /var/log/acpid.log does not exist -- skipping
not running postrotate script, since no logs were rotated

rotating pattern: /config/log/fail2ban/fail2ban.log  weekly (7 rotations)
empty log files are rotated, old logs are removed
considering log /config/log/fail2ban/fail2ban.log
error: skipping "/config/log/fail2ban/fail2ban.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.

rotating pattern: /config/log/letsencrypt/*.log  weekly (52 rotations)
empty log files are not rotated, old logs are removed
considering log /config/log/letsencrypt/letsencrypt.log
error: skipping "/config/log/letsencrypt/letsencrypt.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
...
```
### Now running chmod from my commit:
```
root@efa02cd3fb70:/$ chmod -R u=rwX,g=rX,o=rX /config/log
root@efa02cd3fb70:/$ logrotate -d /etc/logrotate.conf 
reading config file /etc/logrotate.conf
including /etc/logrotate.d
reading config file acpid
reading config file fail2ban
reading config file lerotate
reading config file nginx
reading config file php-fpm7
Allocating hash table for state file, size 64 entries

Handling 5 logs

rotating pattern: /var/log/acpid.log  weekly (4 rotations)
empty log files are not rotated, old logs are removed
considering log /var/log/acpid.log
  log /var/log/acpid.log does not exist -- skipping
not running postrotate script, since no logs were rotated

rotating pattern: /config/log/fail2ban/fail2ban.log  weekly (7 rotations)
empty log files are rotated, old logs are removed
considering log /config/log/fail2ban/fail2ban.log
  log does not need rotating (log has been already rotated)
rotating pattern: /config/log/letsencrypt/*.log  weekly (52 rotations)
empty log files are not rotated, old logs are removed
considering log /config/log/letsencrypt/letsencrypt.log
...
```

**Comment by aptalca** [comment]
Hi Jeff,

Your logs brought something to my attention: `Set "su" directive in config file to tell logrotate which user/group should be used for rotation.` Not sure if it works in alpine, but worth a try. It might let us keep the logs owned by abc:abc

**Comment by aptalca** [comment]
Well, whaddya know. Adding the `su abc abc` statement works in alpine as well. So no need to modify permissions on the log files, they'll be the same as all other files in the config folder. We'll update the images shortly

**Comment by jeffglover** [comment]
An even better solution. Thanks for looking into it!

**Pull request closed without merging**
